### PR TITLE
Install Magento via composer

### PR DESCRIPTION
**Pull request by sreichel**
@cmuench https://github.com/netz98/n98-magerun/issues/1275#issuecomment-1559167049

Updated `config,yml` to get Magento via composer. Replaced magento-mirror with `firegento/magento`

__Notes:__

- had to remove <1.7.0.2 and MagePlus
- 1.9.4.2-1.9.4.5 is not supported atm ... @Schrank you are one of the firegento maintainers. Is it possible for you to add these?

### CODE REVIEW

**Comment by cmuench** [comment]
@sreichel With this approach we will have a major break for people with own installation sources.
Means that we have to increase the major version to `3.0.0`.

**Comment by sreichel** [comment]
@cmuench should we revert it? I have no idea to make it work with old config structure.

**Comment by cmuench** [comment]
@sreichel no. In the meantime the installation works.
It's ok to have a major break but we have to communicate it.

**Comment by sreichel** [comment]
@cmuench okay, just need some Simon :p to add latest release to `firegento/magento`.

**Pull request merged**
